db:
  username: ${username.value:postgres}
  password: Wcwcwc123
  driver: PostgresDriver
  url: postgres:5432
  hosts: localhost,127.0.0.1
  properties:
    first: 123
    second: 567
    third.value: Third
  pool:
    size: 12
    timeout: 10
  pools:
    - size: 1
      timeout: 1
    - size: 2
      timeout: 2
    - size: 3
      timeout: 3

logging:
  level:
    root: INFO
    org.nickz.spring.database.pool: INFO
    org.springframework.jdbc.core: TRACE
  file:
    name: nickz.log
    path: /

spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
    format:
      date: iso
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: Wcwcwc123
    url: jdbc:postgresql://localhost:5432/postgres

  jpa:
    properties:
      hibernate:
        batch_size: 50
        fetch_size: 50
        show_sql: true
        format_sql: true
        hbm2ddl:
          auto: validate
    open-in-view: false

  security:
    oauth2:
      client:
        registration:
          google:
            clientId: ***
            clientSecret: ***
            redirectUri: http://localhost:8080/login/oauth2/code/google
            scope: openid,email,profile

  messages:
    basename: messages

springdoc:
  swagger-ui:
    oauth:
      client-id: ***
      client-secret: ***
      scopes: openid,email,profile
    oauth2-redirect-url: http://localhost:8080/swagger-ui/oauth2-redirect.html

#spring.profiles.act ive:qa
